name: Run Tests on Implementation in 🇨

on:
    push:
        branches: main
    pull_request:
        branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: 📥 Install dependencies
        run: |
            chmod +x setup-py.sh
            sudo ./setup-py.sh
            chmod +x setup-C.sh
            sudo ./setup-C.sh

      - name: ✅ Run tests
        working-directory: ./method-C
        run: |
            chmod +x check.sh
            ./check.sh 2>&1 | tee tests_results.txt
        
      - name: 🖼️ Generate Images
        run: |
          chmod +x image-generator.sh
          ./image-generator.sh -c --all

      - name: 📦 Prepare artifact directory
        if: always()
        run: |
          mkdir -p upload/tests-out
          cp ./method-C/tests_results.txt upload || echo "ERROR"
          cp -r tests-out/method-C/* upload/tests-out || echo "ERROR"
          cp -r images/ upload || echo "ERROR"
          
          # Rename file extension: "out-method-C.png" -> "out.png"
          find . -type f -iname "*out-method-C.png" -exec bash -c 'for f; do mv "$f" "${f/out-method-C.png/out.png}"; done' _ {} + || echo "ERROR"


      - name: 💾 Upload test logs as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checker-logs
          path: upload

          retention-days: 7
