name: Run Tests on Implementation in 🇨

on:
    push:
        branches: main
    pull_request:
        branches: main

defaults:
  run:
    working-directory: ./method-C

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: 📥 Install dependencies
        run: |
            chmod +x setup.sh
            sudo ./setup.sh

      - name: ✅ Run tests
        run: |
            chmod +x check.sh
            ./check.sh 2>&1 | tee tests_results.txt
      
      - name: 🖼️ Generate Images
        run: |
          chmod +x image-generator.sh
          ./image-generator.sh -c --all

      - name: 💾 Upload test logs as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checker-logs
          path: |
            ./method-C/tests_results.txt
            # Without `*` globbing, folders files will not be uploaded
            tests-out/*
            images/*
          retention-days: 7